sudo: required
dist: trusty
language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev valgrind
  - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  - sudo tar xf release-1.7.0.tar.gz
  - cd googletest-release-1.7.0
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - which valgrind
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - make test
  - cd bin && ./enum_flags_unittest
  - cd .. && python third_party/cpplint-1.3.0/cpplint.py --recursive src tests
